### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by YSSkywalker** [EngineersJP/ocr_documet_app#5]
The error message below is show on heroku app of Flask
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by YSSkywalker** [comment]
The logs of 500 Internal ServerError is below.

```
app[web.1]: [2020-09-02 02:34:07,546] ERROR in app: Exception on / [POST]
app[web.1]: Traceback (most recent call last):
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
app[web.1]: response = self.full_dispatch_request()
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
app[web.1]: rv = self.handle_user_exception(e)
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
app[web.1]: reraise(exc_type, exc_value, tb)
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
app[web.1]: raise value
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
app[web.1]: rv = self.dispatch_request()
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
app[web.1]: File "/app/main.py", line 42, in post
app[web.1]: f.save(filepath)
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/werkzeug/datastructures.py", line 3066, in save
app[web.1]: dst = open(dst, "wb")
app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'src/img/03.png'
app[web.1]: 10.159.167.232 - - [02/Sep/2020:02:34:07 +0000] "POST / HTTP/1.1" 500 290 "https://murmuring-island-16454.herokuapp.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36"
heroku[router]: at=info method=POST path="/" host=murmuring-island-16454.herokuapp.com request_id=149c4880-1e79-473d-9906-4e9b9c91c456 fwd="220.98.52.117" dyno=web.1 connect=5ms service=42ms status=500 bytes=470 protocol=https
```

**Comment by YSSkywalker** [comment]
The latest master branch `040ed0b18f3a6972aaf3e839168bf29b49ebcc14` solved this issue.
