### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by YSSkywalker** [EngineersJP/ocr_documet_app#6]
The error message shown is the one below.
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by YSSkywalker** [comment]
the logs;

```
app[web.1]: Traceback (most recent call last):
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
app[web.1]: response = self.full_dispatch_request()
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
app[web.1]: rv = self.handle_user_exception(e)
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
app[web.1]: reraise(exc_type, exc_value, tb)
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
app[web.1]: raise value
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
app[web.1]: rv = self.dispatch_request()
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
app[web.1]: File "/app/main.py", line 44, in post
app[web.1]: image, result = ocr_jpn(filepath)
app[web.1]: File "/app/main.py", line 18, in ocr_jpn
app[web.1]: result = pytesseract.image_to_string(image, lang='jpn')
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 358, in image_to_string
app[web.1]: }[output_type]()
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 357, in <lambda>
app[web.1]: Output.STRING: lambda: run_and_get_output(*args),
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 266, in run_and_get_output
app[web.1]: run_tesseract(**kwargs)
app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 238, in run_tesseract
app[web.1]: raise TesseractNotFoundError()
app[web.1]: pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.
```
